# Generated by Django 4.2.7 on 2024-01-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0013_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Shop', 'Shop'), ('Cleaning', 'Cleaning'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=20),
        ),
    ]
